"""user add forgot_password column

Revision ID: ed299ab0cef0
Revises: 232c8e129453
Create Date: 2025-07-07 15:47:17.310393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed299ab0cef0'
down_revision = '232c8e129453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('forgot_password')

    # ### end Alembic commands ###
